import 'dart:async';
import 'package:dartantic_interface/dartantic_interface.dart';
import '../state/node_context.dart';
import '../state/graph_state_impl.dart';

/// Node in the workflow graph
abstract interface class WorkflowNode {
  /// Unique identifier for this node
  String get id;
  
  /// Node type (for debugging and introspection)
  String get type;
  
  /// Human-readable description
  String get description;
  
  /// Execute this node with the given context
  Stream<NodeResult> execute(
    NodeContext context,
    GraphState state,
  );
  
  /// Validate node configuration
  bool validate();
  
  /// Get list of node IDs this node depends on
  List<String> get dependencies;
}

/// Result from node execution
class NodeResult {
  /// Text output from node
  final String output;
  
  /// Messages generated by node
  final List<ChatMessage> messages;
  
  /// Structured data to share with other nodes
  final Map<String, dynamic> data;
  
  /// Whether node completed successfully
  final bool isSuccess;
  
  /// Error message if failed
  final String? error;
  
  /// Metadata from node execution
  final Map<String, dynamic> metadata;
  
  const NodeResult({
    required this.output,
    required this.messages,
    required this.data,
    required this.isSuccess,
    this.error,
    this.metadata = const {},
  });
  
  const NodeResult.success({
    required this.output,
    required this.messages,
    required this.data,
    this.metadata = const {},
  }) : isSuccess = true, error = null;
  
  const NodeResult.error({
    required this.error,
    this.output = '',
    this.messages = const [],
    this.data = const {},
    this.metadata = const {},
  }) : isSuccess = false;
}
