// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/document_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5875722473398077347),
      name: 'DocumentEntity',
      lastPropertyId: const obx_int.IdUid(5, 2293662676732617696),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6478079222426070870),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4084203261038816665),
            name: 'docId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 5066830926215235051)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8061874461654124227),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1772808138734159827),
            name: 'metadataJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2293662676732617696),
            name: 'embedding',
            type: 28,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5875722473398077347),
      lastIndexId: const obx_int.IdUid(1, 5066830926215235051),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentEntity: obx_int.EntityDefinition<DocumentEntity>(
        model: _entities[0],
        toOneRelations: (DocumentEntity object) => [],
        toManyRelations: (DocumentEntity object) => {},
        getId: (DocumentEntity object) => object.id,
        setId: (DocumentEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentEntity object, fb.Builder fbb) {
          final docIdOffset = fbb.writeString(object.docId);
          final contentOffset = fbb.writeString(object.content);
          final metadataJsonOffset = fbb.writeString(object.metadataJson);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListFloat32(object.embedding!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, docIdOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addOffset(3, metadataJsonOffset);
          fbb.addOffset(4, embeddingOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final docIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final metadataJsonParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final embeddingParam =
              const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final object = DocumentEntity(
              docId: docIdParam,
              content: contentParam,
              metadataJson: metadataJsonParam,
              embedding: embeddingParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentEntity] entity fields to define ObjectBox queries.
class DocumentEntity_ {
  /// See [DocumentEntity.id].
  static final id =
      obx.QueryIntegerProperty<DocumentEntity>(_entities[0].properties[0]);

  /// See [DocumentEntity.docId].
  static final docId =
      obx.QueryStringProperty<DocumentEntity>(_entities[0].properties[1]);

  /// See [DocumentEntity.content].
  static final content =
      obx.QueryStringProperty<DocumentEntity>(_entities[0].properties[2]);

  /// See [DocumentEntity.metadataJson].
  static final metadataJson =
      obx.QueryStringProperty<DocumentEntity>(_entities[0].properties[3]);

  /// See [DocumentEntity.embedding].
  static final embedding =
      obx.QueryDoubleVectorProperty<DocumentEntity>(_entities[0].properties[4]);
}
